"""comments

Revision ID: 3bb335bb7123
Revises: 6f9dfbda1932
Create Date: 2024-04-27 16:24:19.391481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb335bb7123'
down_revision: Union[str, None] = '6f9dfbda1932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('image_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'images', ['image_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'image_id')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
