"""add_nultable_to_images

Revision ID: 49f18434f59c
Revises: 3bb335bb7123
Create Date: 2024-04-28 15:46:14.076757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f18434f59c'
down_revision: Union[str, None] = '3bb335bb7123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('images', 'qr_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'qr_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('images', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
