"""del_foreignkey_comment_id_in_images

Revision ID: 986a2816dcd8
Revises: 49f18434f59c
Create Date: 2024-04-28 17:30:30.132339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986a2816dcd8'
down_revision: Union[str, None] = '49f18434f59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_comment_id_fkey', 'images', type_='foreignkey')
    op.drop_column('images', 'comment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('images_comment_id_fkey', 'images', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###
