PERMISSION_ERROR = "Permission denied"
FILE_NOT_FOUND = "File not found"
DATABASE_ERROR = "Database is not configured correctly"
CONNECT_DATABASE_ERROR = "Failed to connect to the database"
GREETING = "Welcome to FastAPI!"
ADD_TAG_SUCCESS = "Tag added to image successfully"
ADD_COMMENT_SUCCESS = "Comment added successfully"
